### ISSUE TITLE
Use cases for separate network types

### ISSUE THREAD

**Issue by johnbillion** [jeremyfelt/multisite-notes#5] opened 2014-11-25 20:50 UTC
Comment here with example of use cases of multisite which would fit nicely into a network type. For example, social network, corporate website, open blogging platform, etc. The more detail the better.

**Comment by JJJ** [comment] 2014-11-25 22:32
### "Blog" Network

A blogging network, similar to WordPress.com. Users are able to create blogs, pick themes, invite other users, modify settings on their blogs, and essentially own their own sites.

This type of network should use the current WordPress Multisite settings, or some variation there-of, to minimize confusion and provide a backwards compatible experience.

For now, this is the only type or network WordPress ships with.

### "Social" Network

A social network, likely enabled by BuddyPress. Users are only able to create blogs when that functionality is explicitly enabled. Typical user accounts are unable to access `wp-admin` on (at least) the "root site" of the network, if not all other sites (dependent on their roles on each site.)

Users have profiles, are trusted to interact with each other based on features enabled in BuddyPress (Private Messages, Friends, Activity, etc...) and some control over non-root-site content is relinquished to a loosely moderated community of registered members.

This type of network would come with a specific set of network and root-site options to facilitate the easy roll-out of a BuddyPress powered social network. Settings like `illegal_names` would have additional values, welcome email verbiage would be overridden, and root files like `wp-signup.php` and `wp-login.php` may be bypassed to keep users within the familiar WordPress theme.

BuddyPress could ship with this network option by default.

### "Support" Network

A support network, likely enabled with bbPress. Users likely are not able to create blogs, though it may be a feature of a separate but connected blogging network.

Users are trusted to create & edit only specific content types under specific conditions, allowed by roles and capabilities. Some users may have heightened capabilities in specific areas, and be blocked from accessing other areas completely. Consider wordpress.org/support/ where users, moderators, and key masters abound; but also, some users should be allowed limited moderation abilities to topics for plugins and themes under their control.

### "Shopping" Network

A shopping network, likely enabled with Ecommerce software. Users likely are not able to create blogs/sites/stores, have limited or no access to `wp-admin`, etc... Imagine each site in the network is a store-front, requiring some manual approval process before a subdomain and admin access are granted.

Similar to a targeted "Blogging" network, a "Shopping" network assumes each site in the network is owned by someone, and that someone is solely responsible for that content.

### "Intranet" Network

An internal network, likely protected from prying eyes behind additional authentication. Users are "trusted" to be good (for the most part) and may be empowered to perform most CRUD actions on most content.

### "Collaboration" Network

A network used for storing documents and data, loosely matching behavior of the BuddyPress & bbPress codex's. Users are provided heightened capabilities to create & modify content. These users may or may not be trusted, so features like `unfiltered_html` may be conditional or situational.

Users will likely only have access to content, and not themes, plugins, tools, settings, etc... They are basically Contributors, with trusted Editors or Admins moderating and merging content as they see fit.

### All Networks

Registration may be open or closed. Users may or may not be invited. Explicit areas may be public or private. Some options are not unique to any network type, though they do infer a specific set of intentions.

**Comment by earnjam** [comment] 2014-11-25 22:50
### "Protected" Network

An external facing network of affiliated, but separate sites. Perhaps a company, school or other organization which has a number of sites which fall under one primary domain (or not with the help of domain mapping), but essentially operate independently. 

Network is tightly controlled. New site registration would be closed to only super admins. New user registration would likely be closed, but might be open depending on the nature of the network. Both themes and plugins would be available to admins only on a site by site basis.

**Comment by cfoellmann** [comment] 2014-11-25 22:54
@earnjam "Extranet", maybe?
You talk about Domain Mapping. Watch the video I linked to in the other issue. Covers everything this discussion is about. 
The best - no need for Domain Mapping anymore. At least the way it commonly used.

**Comment by earnjam** [comment] 2014-11-25 23:05
Yeah, "Extranet" would work too. 

I didn't have a good name for it, so just went with enterprise because that's what it gets referred to as a lot where I work. We run two multisite networks at UNC Chapel Hill. One is open "Blog" Network like JJJ mentioned above for anyone with university login to create new sites as they wish, and the other is closed network that is commonly referred to as the "enterprise" WordPress network where we host all of our official department/division/school sites.

**Comment by JJJ** [comment] 2014-11-25 23:08
Maybe "Protected" network vs. "Extranet" or "Enterprise"?

Something to indicate that network is under a strict watch?

**Comment by earnjam** [comment] 2014-11-25 23:09
Yeah, I like that better. I'll update the comment.

**Comment by paaljoachim** [comment] 2014-11-25 23:59
<b>The Extended Network</b>

A network connection screen to connect with other sites located on other domains.
Login and see what needs updating for each different site.
A kind of extended network of sites that would be great for a web developer managing multiple web sites for customers to have access to.
Another dimension of connecting ones own sites or customers site to the web developers network hub.

**Comment by cfoellmann** [comment] 2014-11-26 00:05
@paaljoachim these networks we are talking about here are virtual and running from one shared WP codebase. Update once for all sites.

To manage characteristics of the networks you can use **WP Multi Networks**

**Comment by Ipstenu** [comment] 2015-01-20 21:07
Maybe we're doing this wrong. 

Instead of looking at network types and defining them, maybe we should take the list from #6 and use that to make a good 'start' setup that is 'as secure' as we can be. Lock it all down if the blog is under 30 days old (much like how we use that demarcation for forcing subdomain/subfolder today). For 'older' sites, have a less restrictive default. Assume that if they have open registration, they want to keep it, etc. So you get two 'types'
- New - no user signup
- Existing - honor user signup

In both cases, no new blogs and site admins treated as they are today with Multisite permissions.

Everything ELSE is an option.

And yeah, I know what I just said, but there are just tooooooo many possible permutations for this one to be able to predict user paths with any chance of getting it right.

Then we could, if we wanted, have some default options. Like permalinks today, we default to ugly (pretty, I know about that ticket) and let them customize.

**Comment by johnbillion** [comment] 2015-01-20 21:09
I'm not a fan of "network types" at all, but we wanted to look into it as a possibility anyway. JJJ had some good arguments for it versus a simple open/closed structure.

**Comment by Ipstenu** [comment] 2015-01-20 21:18
His arguments sort of prove that both network types AND a simple closed/open mishegas are anything but.

That said, by having 'suggested settings' like 'family blog' with an example of what some settings you may want to set would have a double service of education and easier use. As soon as we open the door for the settings changes people will want to know what's best, and since that's so freakin' subjective, we can maybe stem the tide. Get rid of the terrible naming convention we've been using at the same time. You have a 'new' Multisite, defaults to locked down. You have an old multisite, defaults to medium lockdown. Then we have suggestions.

**Comment by Fab1en** [comment] 2015-02-13 16:00
I operate a WordPress network similar to the one described by Protected network post above. It's for a publishing company that has several (today around 50) sites, all falling into a primary domain. Each site is managed by one person inside the company, and once the site is OK for publication, it is made public to everybody outside the company.

Here are the issues I have with the current WordPress multisite : 
- There is no new user creation moderation : a network can either be open to everyone to register or closed. I would like to have the possibility to allow registration but each new submission would have to be approved by the network superadmin.
- Same idea for sites : I would like to have a moderation queue for site creation requests
- When site is marked as "deactivated", visitors can not access it, but super admins can. I use this to put a site offline during the content preparation. Then, when the site is ready, I activate it. The issue is that normal site admins that do not have super powers cannot do this. I would like to have an "offline" state where only admin users can see it.

**Comment by Ipstenu** [comment] 2015-02-13 16:17
- Approve users: http://wordpress.org/plugins/wp-approve-user/ should work on Multisite
- Approve sites: https://wordpress.org/plugins/moderate-new-blogs/ 
- Yeaaaah there's a ticket about the stupid that is the active/deactive stuff.

**Comment by bueltge** [comment] 2015-02-13 16:48
+1 for @fab1en topics. I have also similar scenarios on a lot of companies with same issues. Tue biggest one have more as 2500 sites and the administration is not easy, like
User administration
Global comments Redaktion
Site control

**Comment by jeremyfelt** [comment] 2015-02-18 05:55
If you're reading this comment, you would be perfect to—after becoming familiar with the material in this issue—chime in on the new thread at https://make.wordpress.org/core/2015/02/18/multisite-objective-defining-network-types/ with your :thought_balloon:

:+1: :zap:

I'm going to close this as a way of moving the conversation. :)

**Closed as completed by jeremyfelt** 2015-02-18 05:55 UTC
Labels: help wanted

**Comment by mikeschinkel** [comment] 2015-02-18 15:59
Following up on what Ipstenu said, it seems that all these presumed "Network Types" are simply a collection of potential (programmer level) configuration options (so as not to violate the "Decisions, not Options" principle.) If we looked at all potential types, envisioned and not yet envisioned, we would come up with a finite list of (new?) configuration options. 

It would seem the first step then would be to identify and document all these potential configuration options at an atomic level.  From there we could then "map" Network Types to their associated configuration settings. 

Even better, Network Types could then be registered just like how Post Types, Post Statuses and Taxonomies are registered which would make missing out on an important use-case in core much less problematic.  

With this proposed approach everyone both pro and con network types can get their cake and get to eat it too.

**Comment by mikeschinkel** [comment] 2015-02-18 16:20
Another Network Type that I've seen is what I'd call the "Shared Server" network type.  This is a network of completely unrelated sites, often developed by completely different people, but hosted on a single multisite because of a misguided opinion that this makes sense.

I do not advocate this use-case and have even actively fought against it, but it seems there are business consulting firms recommending to IT shops at at least one Fortune 100 company the use of Multisite as a way to have one server host multiple WP sites in part so they can then bill out for IT services to each department that needs a site (in this particular case all sites were intranet sites.)

I have also seen numerous people in forums, on mailing lists and at meetups advocating the use of a single Multisite for hosting all their unrelated clients sites. And I can only assume it is because they don't understand the pros and cons of multisite.  Ugh.

So I would either like to see this made easier (i.e. by being able to export and elsewhere import a single site's data and being able to have plugin that are limited to one site) or better yet, make changes in core that somehow make this use-case impossible in future versions and thus force new installations to use multiple single sites and an admin console instead of one multisite.

**Comment by Ipstenu** [comment] 2015-02-18 16:22
FYI, conversation should be moved to https://make.wordpress.org/core/2015/02/18/multisite-objective-defining-network-types/

Please stop commenting HERE :)

**Comment by mikeschinkel** [comment] 2015-02-18 16:22
Ipstenu: Should I repost my comments above at the new URL?

**Comment by Ipstenu** [comment] 2015-02-18 16:24
Yes please.
